name: CI/CD Workflow

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: Beta_Health 
    if: github.actor == 'mrtroll1'
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        
      - name: Configure Git
        run: |
          git config --global user.email ${{ secrets.GIT_EMAIL }}
          git config --global user.name "mrtroll1"
          
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: luka
          key: ${{ secrets.HETZNER_KEY }}
          passphrase: ${{ secrets.HETZNER_KEY_PASSPHRASE }}
          port: 618
          script: |
            git -C /home/luka/Projects/Beta_Health/Beta_Health_Git pull origin master
            sudo pip install -r /home/luka/Projects/Beta_Health/Beta_Health_Git/Python_files/requirements.txt  
            sudo systemctl restart mybot.service
