name: CI/CD Workflow

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: Beta_Health 
    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: root
        key: ${{ secrets.HETZNER_KEY }}
        passphrase: ${{ secrets.HETZNER_KEY_PASSPHRASE }}
        port: 618
        script: |
          cd /root/Projects/Beta_Health/Beta_Health_Git/
          git pull origin master
          pip install -r Python_files/requirements.txt  
          systemctl restart mybot.service         
        
